name: Rebble

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    needs: setup

    steps:
    - uses: actions/checkout@v1
    - name: Build and test with Rebble
      run: |
        docker run --rm -i \
           -v $(pwd):/work \
           -v /tmp/.X11-unix:/tmp/.X11-unix \
           -e DISPLAY=$DISPLAY \
           dmorgan81/rebble build
